name: Bug Report
description: File a bug report to help us improve ColliderTracker
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ColliderTracker version
      description: What version of ColliderTracker are you running?
      placeholder: Run `collidertracker --version` and paste the output here
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system are you using?
      placeholder: e.g., Ubuntu 22.04, macOS 14.0, Windows 11
    validations:
      required: true

  - type: dropdown
    id: supercollider-version
    attributes:
      label: SuperCollider Version
      description: What version of SuperCollider are you using? (if applicable)
      options:
        - "3.13.0"
        - "3.12.2"
        - "3.12.1"
        - "3.12.0"
        - "3.11.2"
        - "3.11.1"
        - "3.11.0"
        - "Other (please specify in additional context)"
        - "Not using SuperCollider"
    validations:
      required: false

  - type: checkboxes
    id: audio-setup
    attributes:
      label: Audio Setup
      description: What audio system are you using? (check all that apply)
      options:
        - label: JACK Audio Connection Kit
        - label: PulseAudio
        - label: ALSA
        - label: CoreAudio (macOS)
        - label: ASIO (Windows)
        - label: Other/Unknown

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. You can enable debug logging with `collidertracker --log debug.log` 
        This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, such as screenshots, configuration files, or anything else that might help us understand the issue.
    validations:
      required: false

